pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven {
            url 'https://jitpack.io'
            content { includeGroupByRegex 'com\\.github.*' }
        }
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        google()
        mavenCentral()
        flatDir { dirs "$rootDir/app/libs" }
    }
}

include ':app'
include ':catvod'
include ':chaquo'
include ':quickjs'
rootProject.name = "TV"
